# Generated by Django 5.2.7 on 2025-10-19 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('power', models.IntegerField(verbose_name='Потребление')),
                ('category', models.CharField(verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Потребитель',
                'verbose_name_plural': 'Потребители',
                'db_table': 'consumers',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('calculated_range', models.IntegerField(blank=True, null=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Запас хода',
                'verbose_name_plural': 'Запасы хода',
                'db_table': 'reserves',
                'ordering': ('-date_formation',),
            },
        ),
        migrations.CreateModel(
            name='ConsumerReserve',
            fields=[
                ('pk', models.CompositePrimaryKey('consumer_id', 'reserve_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.IntegerField(default=0)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.consumer')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.reserve')),
            ],
            options={
                'verbose_name': 'м-м',
                'verbose_name_plural': 'м-м',
                'db_table': 'consumer_reserve',
                'ordering': ('pk',),
            },
        ),
    ]
